apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    spec:
      containers:
          - name: pop-stats
            livenessProbe:
              httpGet:
                path: /h
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 8
            env:
              - name: SITE_NAME
                value: "Population Stats Prod"