apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-stats
  labels:
    env: test
spec:
  template:
    spec:
      containers:
      - name: pop-stats
        env:
          - name: SITE_NAME
            value: "Population Stats Test!"
